repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        files: ^workflows/
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.3.3
    hooks:
      - id: pytest
        args: ["-q"]
        additional_dependencies: [
          "temporalio==1.7.0",
          "pydantic==2.9.2",
          "pydantic-settings==2.5.2",
          "structlog==24.2.0",
          "aiohttp==3.10.5",
          "pytest-asyncio==0.24.0",
        ]
        files: ^workflows/tests/
