services:
  - type: pserv
    name: postgres
    env: docker
    docker:
      image: postgres:15
    plan: standard
    disk:
      name: pg-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_DB
        fromGroup: postgres-auth
      - key: POSTGRES_USER
        fromGroup: postgres-auth
      - key: POSTGRES_PASSWORD
        fromGroup: postgres-auth
    healthCheckPath: null
    autoDeploy: true

  - type: pserv
    name: pgbouncer
    env: docker
    docker:
      image: edoburu/pgbouncer:1.21.0
      command:
        - pgbouncer
        - /etc/pgbouncer/pgbouncer.ini
    plan: starter
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: postgres
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        fromGroup: postgres-auth
      - key: DB_PASSWORD
        fromGroup: postgres-auth
      - key: POOL_SIZE
        value: "50"
    files:
      - path: /etc/pgbouncer/pgbouncer.ini
        content: |
          [databases]
          temporal = host=${DB_HOST} port=${DB_PORT} dbname=${POSTGRES_DB} user=${DB_USER} password=${DB_PASSWORD}
          temporal_visibility = host=${DB_HOST} port=${DB_PORT} dbname=${POSTGRES_DB} user=${DB_USER} password=${DB_PASSWORD}

          [pgbouncer]
          listen_addr = 0.0.0.0
          listen_port = 6432
          auth_type = md5
          auth_file = /etc/pgbouncer/userlist.txt
          max_client_conn = 200
          default_pool_size = ${POOL_SIZE}
          server_reset_query = DISCARD ALL
      - path: /etc/pgbouncer/userlist.txt
        content: 
